Min 27 - BE - Lista de tareas
Victorm0612/Minventory pull request #26
Opened 2020-11-08 03:13 UTC by JoseMMC99

2020-11-08 16:39 UTC, AriannyJanse commented on api/api/urls.py
> +    url(r'^task/employeetask/(?P<fk>[0-9]+)/$', taskviews.employee_task)
Sugerencia de cambio para la url:

`url(r'^task/employee-task/(?P<fk>[0-9]+)/$', taskviews.employee_task)`

2020-11-08 18:25 UTC, AriannyJanse requested changes
En el archivo de taskviews se debe reemplazar `@csrf_exempt` por `@api_view(['VERBO HTTP'])
@permission_classes([AllowAny])
@csrf_exempt`
E importar las librerías necesarias

Ver ejemplo en el archivo de userviews.

PD: De esa manera deben quedar todos los archivos de views.

2020-11-08 22:48 UTC, JoseMMC99 commented on api/api/urls.py
> +    url(r'^task/employeetask/(?P<fk>[0-9]+)/$', taskviews.employee_task)
Done

2020-11-09 15:18 UTC, AriannyJanse approved these changes
LG2M

2020-11-09 15:18 UTC, merged